### ISSUE TITLE
Modernization of metadata handling (excluding search)

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#4]
### Plan
- I am not aware of any need to change the format and structure of the current metadata aggregates (apart from https://github.com/datalad/datalad/issues/3105)
- [x] Three separate components for metadata **extraction**, **aggregation** and **access** (not search) https://github.com/datalad/datalad/pull/3134 (note: was closed without merging)

#### Extraction
- [x] fail early on metadata extractor unavailability https://github.com/datalad/datalad/issues/3060
- [x] support a command-like API with proper error reporting via result dicts https://github.com/datalad/datalad/issues/3125
- [x]  ensure no results of old-style path annotation or symlink dereferencing creep into the code -- only base on `status`/`diff`, allow for this state info to be assemble before and readily given to all extractor on start, to speed things up
- [ ] verify that manual extractor nesting works, i.e. implementing an extractor that calls multiple extractors inside and relays their results, as if all extractors would have been enabled manually. Maybe RF part of the extraction code that determines which extractor to run into a MetaExtractor that does exactly that https://github.com/datalad/datalad/issues/2166
- [x] Version each extractor and include extractor's version within extracted metadata https://github.com/datalad/datalad/issues/3013 (what about co-existence of extractor versions, i.e. put the version into the extractor name?)
- [x] report "internal"/generic dataset properties via standard schema.org terms https://github.com/datalad/datalad/issues/3128
- [x] add extractor for "custom", already properly types metadata https://github.com/datalad/datalad/issues/3114
- [x] resolve overlap between `datalad_core` and `custom` metadata extractor
- [ ] update docs on how to provide dataset descriptions and which terms to use https://github.com/datalad/datalad/issues/3107
- [ ] tune extractor result structure to be as simple as possible (ideally plain key-value, with little or no deeper value structure, work with @context) https://github.com/datalad/datalad/issues/2753
- [ ] include proper @context to give value type information https://github.com/datalad/datalad/issues/2726
- [x] introduce configuration naming scheme for arbitrary,per-extractor switches https://github.com/datalad/datalad/issues/2256
- [x] add annex sizes information to metadata https://github.com/datalad/datalad/issues/3020
- [x] `annex` extractor use batch'ed access as much as possible https://github.com/datalad/datalad/issues/2165 
- [ ] define method for an extractor to indicate which metadata is sensitive/contains identifiers (not sure how useful that is, because given enough OK-ish metadata the combination of them can also be identifying) https://github.com/datalad/datalad/issues/1856
- [x] use git annex SHA1 keys when we have to generate an identifier for files committed to Git

#### Aggregation
- [x] make aggregation go through a public API if possible, not tons of private functions (completed in https://github.com/datalad/datalad/pull/3134)
- [x] factor out code that composes the metadata aggregate to enable merging partial updates (just a few files, or just a subset of extractors) 
- [x] factor out code that performs the "summarizing" of content-level metadata in the dataset-level metadata (unique properties). This should become an optional/configurable/replaceable step. In order to be compatible with partial updates (see below), it has to be done last, and probably should be performed after a dedicated (re-)load of content metadata (once it itself has been updated). Related: https://github.com/datalad/datalad/issues/3177
- [ ] switch to whitelisting for unique values https://github.com/datalad/datalad/issues/3135 https://github.com/datalad/datalad/issues/1960
- [x] ensure proper identification of all aggregated metadata https://github.com/datalad/datalad/issues/3113
- [x] use `diff` to determine more precisely when re-aggregation is needed https://github.com/datalad/datalad/issues/3063 https://github.com/datalad/datalad/issues/2164
- [ ] make behavior with unavailable dataset content configurable https://github.com/datalad/datalad/issues/3010
- [x] streamline API and avoid mandatory "options" that always need to be present in common cases https://github.com/datalad/datalad/issues/2772
- [ ] make exclusion of individual subdatasets configurable https://github.com/datalad/datalad/issues/2739
- [x] define criteria when re-aggregated metadata is different enough to warrant a commit https://github.com/datalad/datalad/issues/2715
- make IncompleteResults report more complete whenever aggregation fails https://github.com/datalad/datalad/issues/2049
- [x] avoid absent metadata access warning completely for aggregation, and duplicates on access https://github.com/datalad/datalad/issues/3185
- [x] determine metadata object filenames based on actual content, not just a hand-picked subset of properties, to make it fully deterministic
- [x] consider minimizing interactions with a dataset by building a complete hierarchy of aggregated metadata under `.git/tmp` and replace the old one with this in one go. this should simplify the code quite a bit, as we do not need tracking of what was changed, replaced, removed, added, ...

#### Access
- [ ] ensure to always report the best _available_ metadata https://github.com/datalad/datalad/issues/3055
- [ ] report `hasPart`/`isPartOf` properties for datasets and files respectively on access (implicitely defined in the internal storage structure, hence no need to pollute the extracted metadata with it
